[package]
name = "rusty_logic"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.31.1"
nalgebra = {version = "^0.33", features = ["serde-serialize"]}
serde = {version = "1.0.219", features = ["derive", "rc"]}
serde_json = "1.0.140"
common_macros = "0.1.1"